export const chapter = {
  창세기: "ge",
  출애굽기: "exo",
  레위기: "lev",
  민수기: "num",
  신명기: "deu",
  여호수아: "josh",
  사사기: "jdgs",
  룻기: "ruth",
  사무엘상: "1sm",
  사무엘하: "2sm",
  열왕기상: "1ki",
  열왕기하: "2ki",
  역대상: "1chr",
  역대하: "2chr",
  에스라: "ezra",
  느헤미야: "neh",
  에스더: "est",
  욥기: "job",
  시편: "psa",
  잠언: "prv",
  전도서: "eccl",
  아가: "ssol",
  이사야: "isa",
  예레미야: "jer",
  예레미야애가: "lam",
  에스겔: "eze",
  다니엘: "dan",
  호세아: "hos",
  요엘: "joel",
  아모스: "amos",
  오바댜: "obad",
  요나: "jonah",
  미가: "mic",
  나훔: "nahum",
  하박국: "hab",
  스바냐: "zep",
  학개: "hag",
  스가랴: "zec",
  말라기: "mal",
  마태복음: "mat",
  마가복음: "mark",
  누가복음: "luke",
  요한복음: "john",
  사도행전: "acts",
  로마서: "rom",
  고린도전서: "1cor",
  고린도후서: "2cor",
  갈라디아서: "gal",
  에베소서: "eph",
  빌립보서: "phi",
  골로새서: "col",
  데살로니가전서: "1th",
  데살로니가후서: "2th",
  디모데전서: "1tim",
  디모데후서: "2tim",
  디도서: "titus",
  빌레몬서: "phmn",
  히브리서: "heb",
  야고보서: "jas",
  베드로전서: "1pet",
  베드로후서: "2pet",
  요한1서: "1jn",
  요한2서: "2jn",
  요한3서: "3jn",
  유다서: "jude",
  요한계시록: "rev",
} as const;

type Book = keyof typeof chapter; // 키 타입
export type BookCode = (typeof chapter)[Book]; // 값 타입

type Plan = {
  book: Book;
  date: string;
  dayCount: number;
  end: number;
  start: number;
  img?: string;
  lang?: string;
  videoId?: string;
};

export type BiblePlan = Plan[];

const bookNumberMap: Record<string, number> = {
  창세기: 1,
  출애굽기: 2,
  레위기: 3,
  민수기: 4,
  신명기: 5,
  여호수아: 6,
  사사기: 7,
  룻기: 8,
  사무엘상: 9,
  사무엘하: 10,
  열왕기상: 11,
  열왕기하: 12,
  역대상: 13,
  역대하: 14,
  에스라: 15,
  느헤미야: 16,
  에스더: 17,
  욥기: 18,
  시편: 19,
  잠언: 20,
  전도서: 21,
  아가: 22,
  이사야: 23,
  예레미야: 24,
  예레미야애가: 25,
  에스겔: 26,
  다니엘: 27,
  호세아: 28,
  요엘: 29,
  아모스: 30,
  오바댜: 31,
  요나: 32,
  미가: 33,
  나훔: 34,
  하박국: 35,
  스바냐: 36,
  학개: 37,
  스가랴: 38,
  말라기: 39,
  마태복음: 40,
  마가복음: 41,
  누가복음: 42,
  요한복음: 43,
  사도행전: 44,
  로마서: 45,
  고린도전서: 46,
  고린도후서: 47,
  갈라디아서: 48,
  에베소서: 49,
  빌립보서: 50,
  골로새서: 51,
  데살로니가전서: 52,
  데살로니가후서: 53,
  디모데전서: 54,
  디모데후서: 55,
  디도서: 56,
  빌레몬서: 57,
  히브리서: 58,
  야고보서: 59,
  베드로전서: 60,
  베드로후서: 61,
  요한1서: 62,
  요한2서: 63,
  요한3서: 64,
  유다서: 65,
  요한계시록: 66,
};

export const bookKeyNumber = (book: string): number => {
  return bookNumberMap[book] || 0; // 책이 없으면 0 반환
};
